<a href="https://colab.research.google.com/github/katetarasenko/KURS_3/blob/main/Laba21Sept.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

1.Створіть одновимірний масив (вектор) з першими 20-ма натуральними числами та виведіть його значення.

In [2]:
 n = 20
natural_numbers = []
for i in range(0, n):
    natural_numbers = natural_numbers + [i+1]
print(natural_numbers)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20]

Створіть двовимірний масив (матрицю) розміром 4x4, заповніть його одиницями та виведіть його значення.

In [3]:
matrix = np.ones((4, 4), dtype=int)
print(matrix)

[[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]

Створіть масив розміром 5x5, заповніть його випадковими дійсними числами в діапазоні від -1 до 1 та виведіть його значення.

In [4]:
matrix = np.random.uniform(low= -1, high=1, size=(5, 5))
print(matrix)

[[-0.24389645 -0.37699941  0.36262733  0.68411895 -0.87949027]
 [-0.91128615 -0.02995692  0.30551633 -0.67338866  0.34996691]
 [ 0.23098857 -0.70474679  0.02510966  0.16443699  0.94067065]
 [-0.34767249 -0.71681976  0.21954086 -0.08968304 -0.97097667]
 [ 0.5311581  -0.09265784  0.70172273 -0.10182763 -0.61377376]]

Створіть масив розміром 3x3, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [5]:
matrix = np.random.rand(3, 3)
print(matrix)

[[0.05581072 0.41301188 0.53032788]
 [0.60122725 0.63320577 0.95853385]
 [0.3742244  0.36426182 0.66557177]]

Створіть два одновимірних масиви розміром 6, заповніть їх випадковими цілими числами в діапазоні від 1 до 20 та виконайте на них поелементні операції додавання, віднімання та множення.

In [6]:
vector1 = np.random.randint(1, 21, size=6)
vector2 = np.random.randint(1, 21, size=6)
vector_sum = vector1 + vector2
vector_division = vector1 / vector2
vector_product = vector1 * vector2
vector_substraction = vector1 - vector2
print("Vector 1:", vector1)
print("Vector 2:", vector2)
print("Vector Sum:", vector_sum)
print("Vector Division:", vector_division)
print("Vector substraction:", vector_substraction)
print("Vector product:", vector_product)

Vector 1: [20 16  1 20  2  8]
Vector 2: [14 14 12 16 12 15]
Vector Sum: [34 30 13 36 14 23]
Vector Division: [1.42857143 1.14285714 0.08333333 1.25       0.16666667 0.53333333]
Vector substraction: [  6   2 -11   4 -10  -7]
Vector product: [280 224  12 320  24 120]

Створіть дві матриці розміром 3x2 та 2x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 5 та перемножте їх між собою.

In [7]:
matrix1 = np.random.randint(1, 5, size=(3, 2))
matrix2 = np.random.randint(1, 5, size=(2, 4))
result_matrix = np.dot(matrix1, matrix2)
print(matrix1)
print(matrix2)
print(result_matrix)

[[2 3]
 [1 1]
 [1 1]]
[[3 1 4 4]
 [1 1 2 3]]
[[ 9  5 14 17]
 [ 4  2  6  7]
 [ 4  2  6  7]]

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [8]:
matrix = np.random.rand(3, 3)
t_mat = matrix.T
print(matrix)
print(t_mat)

[[0.26442192 0.89717618 0.7790633 ]
 [0.57957109 0.96772971 0.12794593]
 [0.82776663 0.8092638  0.56861185]]
[[0.26442192 0.57957109 0.82776663]
 [0.89717618 0.96772971 0.8092638 ]
 [0.7790633  0.12794593 0.56861185]]

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

Створіть дві матриці розміром 3x3, заповніть їх випадковими цілими числами в діапазоні від -5 до 5 та знайдіть їх добуток.

Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від -1 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.



Завдання 2. Робота з бібліотекою Pandas

Відобразити перші 10 рядків таблиці за допомогою методу head

In [9]:
import pandas as pd

In [ ]:
import requests
from bs4 import BeautifulSoup

res = requests.get("https://uk.wikipedia.org/wiki/%D0%9D%D0%B0%D1%80%D0%BE%D0%B4%D0%B6%D1%83%D0%B2%D0%B0%D0%BD%D1%96%D1%81%D1%82%D1%8C_%D0%B2_%D0%A3%D0%BA%D1%80%D0%B0%D1%97%D0%BD%D1%96")
soup = BeautifulSoup(res.text, 'html.parser') #if you find any problem with "lxml" then try using "html.parser" instead
tables = soup.find_all("table", class_="wikitable")
table = tables[10] #Table #11
df = pd.read_html(str(table))[0]
print(df)

In [13]:
df

,рік регіон,1991,1993,1995,1997,1999,2001,2003,2005,2007,2009,2011,2012,2013
0,Автономна Республіка Крим,171,139,125,113,103,103,"▲1,15",121,138,155,156,168,"▼1,66"
1,Вінницька область,198,175,163,151,132,120,"▲1,27",128,137,151,153,159,"▼1,53"
2,Волинська область,212,211,181,171,155,148,"▲1,51",158,171,188,181,192,"▼1,86"
3,Дніпропетровська область,165,142,124,111,100,98,"▲1,09",117,130,145,144,152,"▼1,51"
4,Донецька область,154,131,112,101,89,88,"▲0,94",103,115,129,127,134,"▼1,32"
5,Житомирська область,208,194,169,155,133,122,"▲1,33",139,148,160,165,171,"▼1,68"
6,Закарпатська область,222,202,181,164,145,140,"▲1,49",158,167,183,187,195,"▼1,93"
7,Запорізька область,166,141,123,115,100,100,"▲1,10",116,126,136,137,146,"▼1,43"
8,Івано-Франківська область,214,198,181,167,144,133,"▲1,36",142,150,160,155,163,"▼1,60"
9,Київська область,171,154,140,128,107,105,"▲1,14",126,139,159,158,167,"▼1,64"
10,Кіровоградська область,192,172,152,134,118,112,"▲1,20",123,134,149,151,161,"▼1,57"
11,Луганська область,168,144,120,102,90,88,"▲0,95",99,112,125,127,133,"▼1,30"
12,Львівська область,189,176,163,148,131,124,"▲1,30",136,141,151,149,158,"▼1,55"
13,Миколаївська область,185,160,147,132,113,107,"▲1,17",120,131,145,147,157,"▼1,55"
14,Одеська область,173,153,137,123,110,112,"▲1,21",131,142,158,162,171,"▼1,65"
15,Полтавська область,177,152,137,124,109,99,"▲1,06",108,122,135,133,141,"▼1,40"
16,Рівненська область,221,220,196,186,166,152,"▲1,57",164,176,192,199,208,"▼2,00"
17,Сумська область,171,149,135,121,106,99,"▲1,00",101,115,124,125,136,"▼1,30"
18,Тернопільська область,215,193,179,161,139,123,"▲1,26",131,136,148,145,150,"▼1,48"
19,Харківська область,152,127,114,104,93,91,"▲0,97",103,112,125,125,132,"▬1,32"
20,Херсонська область,191,169,153,138,121,112,"▲1,22",122,138,150,151,161,"▼1,60"
21,Хмельницька область,200,183,167,151,133,124,"▲1,29",132,143,156,156,162,"▼1,61"
22,Черкаська область,189,165,147,138,119,106,"▲1,13",112,125,135,137,143,"▼1,38"
23,Чернівецька область,202,180,171,159,143,129,"▲1,30",138,140,153,158,164,"▼1,63"
24,Чернігівська область,173,158,137,128,112,105,"▲1,13",114,123,134,136,140,"▼1,37"
25,місто Київ,139,111,104,95,87,91,"▲0,98",111,116,130,129,138,"▼1,36"
26,Севастополь (міськрада),...,...,110,102,95,102,"▲1,15",129,136,145,147,162,"▼1,58"
27,Україна,178,156,140,127,113,108,"▲1,15",121,132,145,146,153,"▼1,51"

In [12]:
df.shape

(28, 14)